### ISSUE TITLE
'ChampionGGStats' object has no attribute 'roles' and 'ChampionGGStats' object is not subscriptable

### ISSUE THREAD

**Issue by dawyi** [meraki-analytics/role-identification#2]
i tried to use your code like this : 
```
champion_roles = get_data()
get_roles(champion_roles,['Galio', 'Maokai', 'Jarvan IV', 'Tristana', 'Tahm Kench'])

```
and i got this error : 
```
---> 17         d = {role: champion.championgg[role].play_rate for role in champion.championgg.roles}
AttributeError: 'ChampionGGStats' object has no attribute 'roles'
```
i try to fix this with:
```
d = {role: champion.championgg[role].play_rate for role in ["TOP", "JUNGLE", "MIDDLE", "DUO_CARRY", `"DUO_SUPPORT"]}
```
then i got this : 
```
TypeError: 'ChampionGGStats' object is not subscriptable 
```
is it because i am doing this in the bad way ?

**Comment by xEcEz** [comment]
Two things:

1. I believe the pip release of the championgg cass plugin is not up to date. You can wait for it be released on pip or install the latest version manually.

2. The `get_roles()` function now takes a `List[Champion]` as input, so the call should look like that instead:
`roles, prob, confidence, alternative = get_roles(champion_roles, [Champion(name='Galio', region='NA'), Champion(name='Maokai', region='NA'), Champion(name='Nunu & Willump', region='NA'), Champion(name='Tristana', region='NA'), Champion(name='Tahm Kench', region='NA')], verbose=True)`
