### ISSUE TITLE
Errors & incorrect results

### ISSUE THREAD

**Issue by deekay42** [meraki-analytics/role-identification#6]
roles = {role: Champion(id=id_, region="NA") for role, id_ in roles.items()}

This line crashes because roles.items are already Champion objects.

This is my code:

```
champion_roles = get_data()
match = cass.get_match(2805226856, region="NA")
roles_winning_team = get_team_roles(match.blue_team, champion_roles)
roles_losing_team = get_team_roles(match.red_team, champion_roles)

```

Even then the roles dictionary looks questionable:

`Role.top (4676340704) = {Champion} Champion(name='Ezreal', id=81, region='NA')
Role.jungle (4676340872) = {Champion} Champion(name='Renekton', id=58, region='NA')
Role.middle (4676340816) = {Champion} Champion(name='Viktor', id=112, region='NA')
Role.adc (4676340928) = {Champion} Champion(name='Evelynn', id=28, region='NA')
Role.support (4676340984) = {Champion} Champion(name='Soraka', id=16, region='NA')`

Clearly this is incorrect

**Comment by jjmaldonis** [comment]
Using your same code (or a slight variation on it) I get results that look correct:

Code:

```    
champion_roles = get_data()
match = cass.get_match(2805226856, region="NA")
roles_winning_team = get_team_roles(match.blue_team, champion_roles)
roles_losing_team = get_team_roles(match.red_team, champion_roles)
for role, champion in roles_winning_team.items():
    print(role.name, champion.name)
print()
for role, champion in roles_losing_team.items():
    print(role.name, champion.name)
```

Results:
```
top Renekton
jungle Evelynn
middle Viktor
adc Ezreal
support Soraka

top Darius
jungle Rengar
middle Twisted Fate
adc Draven
support Karma```

How are you inspecting the dictionaries? Or can you give me more information to reproduce your results?
