### ISSUE TITLE
ValueError: The composition was predefined by the kwargs.

### ISSUE THREAD

**Issue by PupsDev** [meraki-analytics/role-identification#9]
I tried to use the role-identification example, with a small set of champion ids to try but I keep getting this error unless I paste the exact example.

Error : 
Traceback (most recent call last):
  File "cass.py", line 18, in <module>
    main()
  File "cass.py", line 13, in main
    roles = get_roles(champion_roles, champions)
  File "C:\Users\Pups\AppData\Local\Programs\Python\Python35-32\lib\site-packages\roleidentification\get_roles.py", line 137, in get_roles
    positions, metric, confidence, sbp = get_positions(champion_positions, composition, **kwargs)
  File "C:\Users\Pups\AppData\Local\Programs\Python\Python35-32\lib\site-packages\roleidentification\get_roles.py", line 37, in get_positions
    raise ValueError("The composition was predefined by the kwargs.")
ValueError: The composition was predefined by the kwargs.

Script : 
from roleidentification import pull_data, get_roles

def main():
    print("Pulling data...")
    champion_roles = pull_data()
    print("Finished pulling data.")
    print()

    champions = [164, 37, 104, 82, 51, 267, 2, 245]  # ['Darius', 'Lee Sin', 'Cassiopeia', 'Draven', 'Braum']
   
    roles = get_roles(champion_roles, champions)
    print(roles)

if __name__ == "__main__":
    main()

**Comment by jjmaldonis** [comment]
The error message isn't very helpful, but why do you have 8 champion IDs in the list? The champions list should be a team composition (so 5 champions).

**Comment by PupsDev** [comment]
Ah thanks ! I didn't think the input must be a single team composition!
